# Generated by Django 4.1.7 on 2023-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='generate_expiring_links',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='include_original_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='thumbnail_size_200',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='thumbnail_size_400',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('B', 'Basic'), ('P', 'Premium'), ('E', 'Enterprise'), ('A', 'Arbitrary')], default='B', max_length=1),
        ),
    ]
