# Generated by Django 4.1.7 on 2023-03-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounttier_remove_account_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttier',
            old_name='expiring_link_enabled',
            new_name='expiring_url',
        ),
        migrations.RenameField(
            model_name='accounttier',
            old_name='original_link_enabled',
            new_name='original_url',
        ),
    ]
