# Generated by Django 4.1.7 on 2023-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_remove_image_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/'),
        ),
    ]
