# Generated by Django 4.1.7 on 2023-03-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
    ]
